import setuptools

with open("README.md", encoding="utf8") as f:
    long_description = f.read()

setuptools.setup(
    name="UppaalLTLParser",
    version="0.1.0",
    description="A pure-python tool to parse CTL rules generated by UPPAAL.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/hzyrc6011/UppaalLTLParser",
    author="hzyrc6011",
    author_email="zhanyihou6011@gmail.com",
    license="MIT",
    # For classifiers, refer to:
    # https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#classifiers
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: Unix",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python :: 3",
        "Topic :: Software Development",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    project_urls={
        "Documentation": "https://hzyrc6011.github.io/UppaalLTLParser/",
    },
    packages=setuptools.find_namespace_packages(
        include=["UppaalLTLParser", "UppaalLTLParser.*"]
    ),
    install_requires=[
    ],
    include_package_data=True,
)
